env = Environment(tools=["default", "arduino"],
                          UPLOAD_PORT="/dev/ttyACM0")
env.ConfigureBoard("uno")
core = env.ArduinoCore()

sketch = env.Sketch("artemis_arduino", ["main.cpp", core])
env.Upload(sketch)
