import os

env = Environment(CC = 'g++',
                  CPPFLAGS='--std=c++11')

for root, subdirs, files in os.walk(os.curdir):
    for filename in files:
        if filename == "SConscript":
            SConscript(os.path.join(root, filename), variant_dir= os.path.join(root, "build"), duplicate = 0, exports='env')
