Import('ardenv')

ardenv.Append( CPPPATH = ['#lib/motor_control'
                            ],
                )

ardenv.ConfigureBoard("uno")
core = ardenv.ArduinoCore()

motor_control = ardenv.ArduinoLibrary('motor_control', '#lib/motor_control')

sketch = ardenv.Sketch("artemis_arduino", ["main.cpp", motor_control, core])
ardenv.Upload(sketch)
